replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-quarkus-mvn-jenkins-eve/fruit@sha256:d27369a05098b91bd2195b7c8c5a9938aa8716542aaa5537351ff4cbf1c0f5a5 # written by ploigos-step-runner
